### ISSUE TITLE
QueryKey

### ISSUE THREAD

**Issue by mgarf** [rosh93/meteor-dataset-filter#1]
Hi,

I saw this package and it fits perfectly into what I am building. my hope though is that I can assign it more than one QueryKey. How would I go about doing that? 

I tried feeding it an array but it seems your code doesn't accept array of data. Any other thoughts to how I can query two fields with one input?

**Comment by rjobanp** [comment]
Hi @mgarf .

I just published a release `0.0.6` that adds support for arrays of `queryKey`'s. Let me know if that works for you.

**Comment by mgarf** [comment]
Thank you @rosh93 for the quick response and fix. I have looked at your other meteor packages and its all great :)
